name: Generate TOC

on:
  push:
    branches:
      - master

jobs:
  toc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate TOC
        run: |
          npm install -g markdown-toc
          markdown-toc -i README.md
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Generate TOC'
          git push
